name: Bug Report
description: Create a report to help us improve
title: "[BUG]"
labels: ["bug :bug:"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting issues of python-telegram-bot!

        Use this template to notify us if you found a bug.

        To make it easier for us to help you please enter detailed information below.

        Please note, we only support the latest version of python-telegram-bot and
        master branch. Please make sure to upgrade & recreate the issue on the latest
        version prior to opening an issue.
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      value: |
        1. 

        2.

        3.
        
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: Tell us what should happen
    validations:
      required: false
      
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
      description: Tell us what happens instead
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: "### Configuration"

  - type: input
    id: operating-system
    attributes:
      label: Operating System
    validations: 
      required: false

  - type: textarea
    id: versions
    attributes:
      label: Version of Python, python-telegram-bot & dependencies
      description: This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations: 
      required: false
      
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
